### ISSUE TITLE
[question] Why only a single file?

### ISSUE THREAD

**Issue by deeprobin** [LabyStudio/singlehotswap#3]
You could go through the whole source set and use the file hashes to check if the file has been changed (like [Git](https://github.com/git/git/blob/49f38e2de47a401fc2b0f4cce38e9f07fb63df48/hash.h#L8) does).

Git uses SHA1, but I would recommend some faster non-cryptographic alternatives (see references).

This could be combined with directory watching¹ to improve the performance.

### References
* [CRC32](https://en.wikipedia.org/wiki/Cyclic_redundancy_check)
* [XXH3](https://github.com/Cyan4973/xxHash)

### Foot Note
\[1\]: https://stackoverflow.com/questions/23452527/watching-a-directory-for-changes-in-java

**Comment by LabyStudio** [comment]
The basic idea behind this plugin is that we needed to hotswap specific files.

If you are working on a project with a lot of bytecode manipulation, you don't want to hotswap the wrong class because that would mess up everything. (IntelliJ's built-in hotswapping feature hotswaps everything related to the target class)

So basically the plugin is designed to hotswap small things in your code very quickly.
But a feature like you suggested might be an additional feature to think about.
