### ISSUE TITLE
Suggestion: New UI Support

### ISSUE THREAD

**Issue by NxDs** [LabyStudio/singlehotswap#5]
IntelliJ 2022.3 introduced the option to use a new UI in beta, would be nice to have the plugin support that one as well since the icon doesn't currently show up

**Comment by LabyStudio** [comment]
Added support in v2.2

**Comment by OnePros** [comment]
Nx I get not wanting to come back, but please at least give Hyper or myself the perms to try and work some stuff out, I get GitHub ain't the way but there's no other way things will work out. Unless you're coming back but it doesn't look like it since Dieu is unresponsive. This will be my only comment, I apologise for the annoyance but it's bad. Really, bad. I'm sorry I had to contact you like this @NxDs . I am.
